# This rule is not used by the project learn itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over eighth.cloudclub.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: learn
    app.kubernetes.io/managed-by: kustomize
  name: myapp-admin-role
rules:
- apiGroups:
  - eighth.cloudclub.com
  resources:
  - myapps
  verbs:
  - '*'
- apiGroups:
  - eighth.cloudclub.com
  resources:
  - myapps/status
  verbs:
  - get
